### ISSUE TITLE
Exit with code 1 due to network error: ProtocolUnknownError

### ISSUE THREAD

**Issue by luckylittle** [HAKSOAT/EpubToPdf#3]
There are certain types of EPUB files, which refer to object(s) using the relative path, as oppose to absolute path - e.g.:

```html
<img alt="97.tif" class="image" src="../Images/97_fmt.jpeg" width="19%" />
```

In those cases, the `main.py` will fail to convert with the following error:

```text
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: ProtocolUnknownError
```

The solution for this is to add the following option on [line 36 in pdfpy.py](https://github.com/HAKSOAT/EpubToPdf/blob/master/pdfpy.py#L36)

```python
options = {
	"enable-local-file-access": None,
	"quiet": ""
}
```

**Comment by ucalyptus** [comment]
@luckylittle make a PR , I will use your fork then.

**Comment by HAKSOAT** [comment]
Fix added @luckylittle Thanks for pointing out
